(() => {
'use strict';const D=window.PILOT,$=s=>document.querySelector(s);if(!D||!window.L){$('#cell-title').textContent='Map unavailable';return;}
let layer='vegetation',selected=null;const all=new Map([...D.features,...D.coarseFeatures].map(f=>[f.properties.cell_id,f]));const fmt=(v,n=1)=>Number.isFinite(v)?v.toFixed(n):'—',sign=v=>Number.isFinite(v)?(v<0?'−':'+')+Math.abs(v).toFixed(3):'—';
const layers={vegetation:{title:'greennessLegend',note:'greennessNote',colors:['#697964','#90a973','#bad58a','#dcf0ae'],labels:['<25%','25–50%','50–75%','≥75%'],get:p=>p.vegetation_pct_valid,bin:v=>v<25?0:v<50?1:v<75?2:3},change:{title:'changeLegend',note:'changeNote',colors:['#b57b53','#ceb28c','#bacaae','#80b29b'],labels:['<−0.10','−0.10–<−0.03','−0.03–<0','≥0'],get:p=>p.delta_NDVI,bin:v=>v<-.10?0:v<-.03?1:v<0?2:3},population:{title:'populationLegend',note:'populationLayerNote',colors:['#778f82','#9abdab','#c2d8bf','#e4ebcf'],labels:['<100','100–<500','500–<1,000','≥1,000'],get:p=>p.population_modelled,bin:v=>v<100?0:v<500?1:v<1000?2:3},satellite:{title:'satelliteLegend',note:'satelliteNote',colors:[],labels:[],get:()=>0,bin:()=>0},boundary:{title:'boundaryLegend',note:'boundaryNote',colors:[],labels:[],get:()=>null,bin:()=>0}};
const controller=createPilotMap(D,id=>select(id),layers);window.GBG_MAP=controller;
function render(){const l=layers[layer];controller.setState({layer,selected,lines:$('#show-grid').checked});$('#legend-title').textContent=tr(l.title);$('#layer-note').textContent=tr(l.note);const el=$('#legend-swatches');el.replaceChildren();l.labels.forEach((txt,i)=>{const span=document.createElement('span'),sw=document.createElement('i');sw.style.background=l.colors[i];span.append(sw,document.createTextNode(txt));el.append(span);});document.querySelectorAll('[data-layer]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layer===layer)));}
function select(id){const f=all.get(id);if(!f)return;selected=id;const p=f.properties;$('#cell-title').textContent=p.grid_m+' '+tr('cellLabel')+' '+p.cell_id.replace(/^50m_/,'').replaceAll('_',' / ');
const stats=[[p.grid_m===250?fmt(p.population_modelled,0):fmt(p.vegetation_pct_valid)+'%',p.grid_m===250?'residentsValue':'greennessValue'],[sign(p.delta_NDVI),'changeValue']];const box=$('#cell-measures');box.replaceChildren();stats.forEach(([v,key])=>{const div=document.createElement('div'),n=document.createElement('strong'),lab=document.createElement('span');n.textContent=v;lab.textContent=tr(key);div.append(n,lab);box.append(div);});$('#ndvi-old').textContent=fmt(p.NDVI_2019,3);$('#ndvi-new').textContent=fmt(p.NDVI_2026,3);for(const [key,v] of[['old',p.NDVI_2019],['new',p.NDVI_2026]])$('#ndvi-'+key+'-bar').style.width=(Number.isFinite(v)?Math.max(0,Math.min(100,v/.8*100)):0)+'%';$('#cell-action').textContent=tr('cellAction');$('#cell-coverage').textContent=tr('coverage')+' '+fmt(p.optical_valid_pct)+'% · '+tr('commonCoverage')+' '+fmt(p.common_valid_pct)+'%';$('#cell-request').href=window.residentHref(p.lat,p.lon,p.cell_id);$('#cell-open').href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.lat+','+p.lon);$('#announcement').textContent=$('#cell-title').textContent;render();}
document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{layer=b.dataset.layer;const fs=layer==='population'?D.coarseFeatures:D.features;const p=all.get(selected)?.properties;if(p&&layer!=='boundary'&&p.grid_m!==(layer==='population'?250:50)){const near=[...fs].sort((a,b)=>Math.hypot(a.properties.lat-p.lat,a.properties.lon-p.lon)-Math.hypot(b.properties.lat-p.lat,b.properties.lon-p.lon))[0];select(near.properties.cell_id);}else render();});$('#show-grid').onchange=render;window.addEventListener('languagechange',()=>{if(selected)select(selected);else render();});
// The handles are the controls: pointer, touch and keyboard share one value.
function drag(handle,frame,get,set){const update=e=>{const r=frame.getBoundingClientRect();set(Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)));};handle.addEventListener('pointerdown',e=>{e.preventDefault();handle.setPointerCapture(e.pointerId);update(e);});handle.addEventListener('pointermove',e=>{if(handle.hasPointerCapture(e.pointerId))update(e);});handle.addEventListener('pointerup',e=>{if(handle.hasPointerCapture(e.pointerId))handle.releasePointerCapture(e.pointerId);});handle.addEventListener('keydown',e=>{let n=get();if(e.key==='ArrowLeft'||e.key==='ArrowDown')n-=e.shiftKey?10:2;else if(e.key==='ArrowRight'||e.key==='ArrowUp')n+=e.shiftKey?10:2;else if(e.key==='Home')n=0;else if(e.key==='End')n=100;else return;e.preventDefault();set(Math.max(0,Math.min(100,n)));});}
document.querySelectorAll('[data-swipe]').forEach(frame=>{let value=50;const handle=frame.querySelector('.swipe-handle');drag(handle,frame,()=>value,n=>{value=n;frame.style.setProperty('--split',n+'%');handle.setAttribute('aria-valuenow',String(Math.round(n)));});});
const frame=$('#satellite-compare');let a=33,b=67;const ha=frame.querySelector('.handle-a'),hb=frame.querySelector('.handle-b');function setTriple(){frame.style.setProperty('--a',a+'%');frame.style.setProperty('--b',b+'%');ha.setAttribute('aria-valuenow',String(Math.round(a)));ha.setAttribute('aria-valuemax',String(Math.round(b-8)));hb.setAttribute('aria-valuenow',String(Math.round(b)));hb.setAttribute('aria-valuemin',String(Math.round(a+8)));}drag(ha,frame,()=>a,n=>{a=Math.min(n,b-8);setTriple();});drag(hb,frame,()=>b,n=>{b=Math.max(n,a+8);setTriple();});setTriple();
const initial=[...D.features].filter(f=>f.properties.projected_area_m2>2300).sort((a,b)=>Math.abs(a.properties.lat-22.794)+Math.abs(a.properties.lon-89.534)-Math.abs(b.properties.lat-22.794)-Math.abs(b.properties.lon-89.534))[0]||D.features[0];select(initial.properties.cell_id);
})();
