(() => {
'use strict';const $=s=>document.querySelector(s),form=$('#resident-form');if(!form)return;const D=window.PILOT;let pin=null,point=null,step=1,caseId='',output=null,cardUrl=null;
const photos=new Map(),versions={},roles=['frontage','surroundings','sidewall','rooftop'];let map=null;
if(window.L){map=L.map('request-map',{zoomControl:true,scrollWheelZoom:false,maxZoom:20,minZoom:3});map.attributionControl.setPrefix('<a href="https://leafletjs.com">Leaflet</a>');
const border=L.geoJSON(D.boundary,{style:{color:'#d5e5a1',weight:2,fill:false,interactive:false}}).addTo(map);map.fitBounds(border.getBounds(),{padding:[15,15]});L.imageOverlay(D.mapImage.file,D.mapImage.bounds,{attribution:'EU/ESA/Copernicus · Sentinel-2, 2026'}).addTo(map);
const tiles=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,maxNativeZoom:19,updateWhenIdle:true,keepBuffer:1,attribution:'Imagery © Esri, Vantor, Earthstar Geographics, GIS User Community'}).addTo(map);let failed=0,loaded=0;tiles.on('tileload',()=>loaded++);tiles.on('tileerror',()=>{if(++failed>=2&&!loaded){map.removeLayer(tiles);if(!point)$('#location-status').textContent=tr('mapOffline');}});border.bringToFront();map.on('click',e=>setPoint(e.latlng.lat,e.latlng.lng));new ResizeObserver(()=>map.invalidateSize({animate:false})).observe($('#request-map'));}
function validPoint(lat,lon){return Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=-90&&lat<=90&&lon>=-180&&lon<=180;}
function setPoint(lat,lon,center=false){if(!validPoint(lat,lon))return;point={lat,lon};$('#latitude').value=lat.toFixed(6);$('#longitude').value=lon.toFixed(6);$('#location-status').textContent=tr('pinSelected');if(map){if(pin)pin.setLatLng([lat,lon]);else{pin=L.marker([lat,lon],{draggable:true,icon:L.divIcon({className:'pin-icon',iconSize:[22,22],iconAnchor:[11,11]})}).addTo(map);pin.on('dragend',()=>{const p=pin.getLatLng();setPoint(p.lat,p.lng);});}if(center)map.setView([lat,lon],17);}}
function queryPoint(){const query=new URLSearchParams(window.SINGLE_FILE?(window.PREVIEW_RESIDENT_QUERY||location.hash.split('?')[1]||''):location.search);if(query.has('lat')&&query.has('lon')){const lat=Number(query.get('lat')),lon=Number(query.get('lon'));if(validPoint(lat,lon))setPoint(lat,lon,true);}}
queryPoint();window.addEventListener('residentroute',()=>{queryPoint();if(map)setTimeout(()=>map.invalidateSize(),20);});
$('#set-coordinates').onclick=()=>{const la=$('#latitude').value,lo=$('#longitude').value;if(!la||!lo||!validPoint(Number(la),Number(lo))){$('#location-status').textContent=tr('coordinatesInvalid');return;}setPoint(Number(la),Number(lo),true);};
$('#use-location').onclick=()=>{if(!navigator.geolocation){$('#location-status').textContent=tr('locateUnsupported');return;}$('#location-status').textContent=tr('locating');navigator.geolocation.getCurrentPosition(p=>setPoint(p.coords.latitude,p.coords.longitude,true),()=>$('#location-status').textContent=tr('locationDenied'),{enableHighAccuracy:true,timeout:12000,maximumAge:60000});};
function error(key){const el=$('#form-error');el.textContent=key?tr(key):'';el.hidden=!key;el.dataset.errorKey=key||'';}
function clearPhoto(role){const old=photos.get(role);if(old)URL.revokeObjectURL(old.url);photos.delete(role);const img=$('#preview-'+role);img.hidden=true;img.removeAttribute('src');$('#filename-'+role).textContent='';img.parentElement.querySelector('.photo-plus').hidden=false;}
document.querySelectorAll('[data-photo-role]').forEach(input=>input.addEventListener('change',async()=>{const role=input.dataset.photoRole,file=input.files[0],version=(versions[role]||0)+1;versions[role]=version;clearPhoto(role);error('');if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){input.value='';error('fileType');return;}if(file.size>10*1024*1024){input.value='';error('fileSize');return;}
const url=URL.createObjectURL(file),test=new Image();test.src=url;try{await test.decode();if(test.naturalWidth*test.naturalHeight>50000000)throw new Error('Image too large');if(versions[role]!==version){URL.revokeObjectURL(url);return;}photos.set(role,{file,url,role});const preview=$('#preview-'+role);preview.src=url;preview.alt=tr('photoRole'+role);preview.hidden=false;preview.parentElement.querySelector('.photo-plus').hidden=true;$('#filename-'+role).textContent=file.name;}catch{URL.revokeObjectURL(url);if(versions[role]===version){input.value='';error('decodeError');}}}));
function showStep(n){step=n;form.hidden=n!==1;$('#request-review').hidden=n!==2;$('#request-result').hidden=n!==3;for(const [i,id] of[[1,'one'],[2,'two'],[3,'three']])$('#progress-'+id).classList.toggle('active',i===n);if(n===1)map?.invalidateSize();const head=n===1?$('.request-heading'):n===2?$('#request-review'):$('#request-result');head.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
function caseData(){return{caseId,createdAt:new Date().toISOString(),language:getLanguage(),location:point,placeName:$('#place-name').value.trim(),improvement:$('#improvement').value,notes:$('#resident-notes').value.trim(),cellId:new URLSearchParams(window.SINGLE_FILE?(window.PREVIEW_RESIDENT_QUERY||''):location.search).get('cell')||null,photoRoles:[...photos.keys()],permissionConfirmed:$('#photo-consent').checked,status:'concept-card',outputMessage:tr('soon')};}
function renderReview(){const data=caseData(),box=$('#review-summary');box.replaceChildren();const div=document.createElement('div');div.className='review-summary';const name=document.createElement('strong');name.textContent=data.placeName||tr('emptyLandmark');const goal=document.createElement('p');goal.textContent=tr('goal'+data.improvement);const loc=document.createElement('p');loc.textContent=tr('chosenLocation')+' · '+point.lat.toFixed(5)+', '+point.lon.toFixed(5);div.append(name,goal,loc);if(data.notes){const p=document.createElement('p');p.textContent=data.notes;div.append(p);}box.append(div);const gallery=$('#review-photos');gallery.replaceChildren();photos.forEach(photo=>{const figure=document.createElement('figure'),im=document.createElement('img'),cap=document.createElement('figcaption');im.src=photo.url;im.alt=tr('photoRole'+photo.role);cap.textContent=tr('photoRole'+photo.role);figure.append(im,cap);gallery.append(figure);});}
form.addEventListener('submit',e=>{e.preventDefault();if(!point){error('noPin');return;}if(!photos.has('frontage')){error('noFrontage');return;}if(!$('#photo-consent').checked){error('noConsent');return;}error('');caseId='GBG-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+(window.crypto?.randomUUID?crypto.randomUUID().slice(0,6):Math.random().toString(36).slice(2,8)).toUpperCase();renderReview();showStep(2);});$('#edit-details').onclick=()=>showStep(1);
function wrap(ctx,text,x,y,maxWidth,lineHeight){const words=text.split(' ');let line='',count=0;for(const word of words){const next=line?line+' '+word:word;if(ctx.measureText(next).width>maxWidth&&line){ctx.fillText(line,x,y+count*lineHeight);count++;line=word;}else line=next;}ctx.fillText(line,x,y+count*lineHeight);return y+(count+1)*lineHeight;}
async function makeCard(){await document.fonts.ready;const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=1000;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');ctx.fillStyle='#f6f3e9';ctx.fillRect(0,0,1600,1000);ctx.strokeStyle='#becdb0';ctx.lineWidth=2;ctx.strokeRect(40,40,1520,920);ctx.fillStyle='#183d2f';ctx.textAlign='left';ctx.font='26px Arial, sans-serif';ctx.fillText('green before grey',110,115);ctx.font='20px Arial, sans-serif';ctx.fillStyle='#718260';ctx.fillText(caseId,110,155);
ctx.fillStyle='#d5e4b4';ctx.beginPath();ctx.arc(1350,210,130,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#537344';ctx.lineWidth=3;for(let i=0;i<3;i++){const x=1300+i*45;ctx.beginPath();ctx.moveTo(x,280);ctx.bezierCurveTo(x-15,200,x+8,180,x+30,130);ctx.stroke();ctx.beginPath();ctx.ellipse(x+10,190,20,38,.55,0,Math.PI*2);ctx.stroke();}
ctx.fillStyle='#183d2f';ctx.font='italic 62px Georgia, "Noto Sans Bengali", "Nirmala UI", serif';ctx.textAlign='left';wrap(ctx,tr('cardTitle'),110,285,1100,78);ctx.fillStyle='#244f39';ctx.fillRect(100,385,1400,280);ctx.fillStyle='#f6f3e9';ctx.textAlign='center';ctx.font='50px Arial, "Noto Sans Bengali", "Nirmala UI", sans-serif';wrap(ctx,tr('soon'),800,500,1240,66);ctx.font='22px Arial, "Noto Sans Bengali", "Nirmala UI", sans-serif';ctx.fillStyle='#d6e5b4';ctx.fillText(tr('cardSub'),800,620);
const d=caseData();ctx.textAlign='left';ctx.fillStyle='#183d2f';ctx.font='27px Arial, "Noto Sans Bengali", "Nirmala UI", sans-serif';wrap(ctx,d.placeName||tr('emptyLandmark'),110,740,1290,38);ctx.font='22px Arial, "Noto Sans Bengali", "Nirmala UI", sans-serif';ctx.fillStyle='#617257';ctx.fillText(tr('goal'+d.improvement)+' · '+photos.size+' '+tr('photoCount'),110,815);ctx.font='italic 24px Georgia, "Noto Sans Bengali", "Nirmala UI", serif';wrap(ctx,tr('cardFooter'),110,905,1300,32);return await new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('PNG encoding failed')),'image/png'));}
let working=false;async function refreshCard(){output=await makeCard();if(cardUrl)URL.revokeObjectURL(cardUrl);cardUrl=URL.createObjectURL(output);$('#result-image').src=cardUrl;$('#result-status').textContent=tr('ready');}
$('#create-card').onclick=async()=>{if(working)return;working=true;$('#create-card').disabled=true;try{await refreshCard();showStep(3);}catch{error('cardError');showStep(1);}finally{working=false;$('#create-card').disabled=false;}};
$('#download-card').onclick=()=>{if(output)downloadBlob(output,caseId+'_Concept_Card.png');};
// ZIP store mode, CRC-32 and UTF-8 names: no CDN or external library required.
const encoder=new TextEncoder(),crcTable=Uint32Array.from({length:256},(_,i)=>{let c=i;for(let b=0;b<8;b++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0;});const crc32=data=>{let c=0xffffffff;for(const byte of data)c=crcTable[(c^byte)&255]^(c>>>8);return(c^0xffffffff)>>>0;};
function record(size){const bytes=new Uint8Array(size),view=new DataView(bytes.buffer);return{bytes,u16:(p,v)=>view.setUint16(p,v,true),u32:(p,v)=>view.setUint32(p,v,true)};}
async function zip(entries){const files=[],central=[];let offset=0;const now=new Date(),dt=((now.getHours()<<11)|(now.getMinutes()<<5)|(now.getSeconds()>>1)),dd=(((now.getFullYear()-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate());for(const entry of entries){const name=encoder.encode(entry.name),bytes=entry.bytes||new Uint8Array(await entry.blob.arrayBuffer()),crc=crc32(bytes),h=record(30);h.u32(0,0x04034b50);h.u16(4,20);h.u16(6,0x800);h.u16(10,dt);h.u16(12,dd);h.u32(14,crc);h.u32(18,bytes.length);h.u32(22,bytes.length);h.u16(26,name.length);files.push(h.bytes,name,bytes);const c=record(46);c.u32(0,0x02014b50);c.u16(4,20);c.u16(6,20);c.u16(8,0x800);c.u16(12,dt);c.u16(14,dd);c.u32(16,crc);c.u32(20,bytes.length);c.u32(24,bytes.length);c.u16(28,name.length);c.u32(42,offset);central.push(c.bytes,name);offset+=30+name.length+bytes.length;}const centralSize=central.reduce((sum,a)=>sum+a.length,0),end=record(22);end.u32(0,0x06054b50);end.u16(8,entries.length);end.u16(10,entries.length);end.u32(12,centralSize);end.u32(16,offset);return new Blob([...files,...central,end.bytes],{type:'application/zip'});}
$('#download-request').onclick=async()=>{const button=$('#download-request');button.disabled=true;try{const entries=[{name:'request.json',bytes:encoder.encode(JSON.stringify(caseData(),null,2))},{name:'concept-card.png',blob:output}];photos.forEach(photo=>{const ext=({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'})[photo.file.type];entries.push({name:'photos/'+photo.role+'.'+ext,blob:photo.file});});downloadBlob(await zip(entries),caseId+'_Photos_and_Details.zip');}catch{$('#result-status').textContent=tr('exportError');}finally{button.disabled=false;}};
$('#start-again').onclick=()=>{roles.forEach(role=>{versions[role]=(versions[role]||0)+1;clearPhoto(role);});form.reset();point=null;if(pin){map?.removeLayer(pin);pin=null;}output=null;if(cardUrl)URL.revokeObjectURL(cardUrl);cardUrl=null;$('#result-image').removeAttribute('src');$('#location-status').textContent='';error('');showStep(1);};
window.addEventListener('languagechange',async()=>{photos.forEach(p=>$('#preview-'+p.role).alt=tr('photoRole'+p.role));if(point)$('#location-status').textContent=tr('pinSelected');const key=$('#form-error').dataset.errorKey;if(key)error(key);if(step===2)renderReview();if(step===3){try{await refreshCard();}catch{$('#result-status').textContent=tr('cardError');}}});
window.GBG_REQUEST={get point(){return point;},get photoCount(){return photos.size;},get step(){return step;},get caseId(){return caseId;},setPoint,map};
})();
